# Site settings
title: Rahul Bhammarker
description: Rahul Bhammarker
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Bhammarker
user_description: A Techonolgy Enthusiast and an Art Lover.
user_title: Software Developer
email: bhammarkerrahul@gmail.com
twitter_username: https://twitter.com/Bhammarkerrahul
github_username:  https://github.com/RahulBhammarker
linkedin_username: https://www.linkedin.com/in/rahulbhammarker/
medium_username: https://medium.com/@bhammarkerrahul
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
